config/routes.rb
Rails.application.routes.draw do

  resources :ratings
  root "application#index"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/signup" => "users#new"
  post "/signup" => "users#create"
  post "/logout" => "sessions#destroy"

  get "/auth/:provider/callback" => "sessions#omniauth"

  resources :trips, only: [:new, :create, :edit, :update, :destroy]

  resources :mountains, only: [:show, :index] do
    resources :trips, only: [:new]
  end

  resources :users, only: [:new, :create, :edit, :show] do
    resources :trips, only: [:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mountain.rb
class Mountain < ApplicationRecord
    has_many :trails
    has_many :trips
    has_many :users, through: :trips

    def mountain_rating
        trail_ratings = []
        self.trails.each do |trail|
            trail_ratings << trail.trail_rating unless trail.trail_rating == 0.0
        end
        if trail_ratings.empty?
            return 0.0
        else
            result = trail_ratings.sum.to_f / trail_ratings.size.to_f
            result.round(2)
        end
    end

    def self.sort_by_rating
        self.all.sort_by {|mountain| mountain.mountain_rating}.reverse
    end

end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
    before_action :require_login

    def index
        @mountains = Mountain.sort_by_rating
        @top_trails = Trail.top_5
        @top_users = User.top_5
    end

    def show
        @mountain = Mountain.find_by(id: params[:id])
    end

end

app/helpers/mountains_helper.rb
module MountainsHelper
end

app/views/mountains/index.html.erb
<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
<% end %>

<div class="container main-features">
  <div class="row">
  <h1>Welcome, <%=current_user.first_name%></h1>
  </div>
  <br>
  <div class="row">
    <div class="col-8">
    <h3 class="main-feature-title">Top Mountains</h3>
    <% @mountains.each do |m| %>
    <div class="row top-buffer">
    <div class="col-2 my-auto">
    <% if current_user.has_visited?(m)%>
    <%= image_tag("#{m.id}.jpg", style: 'margin: auto; width: 100%; border: 1px black') %>
    <% else %>
    <%= image_tag("#{m.id}.jpg", style: 'margin: auto; width: 100%; opacity: 0.5; border: 1px black') %>
    <% end %>
    </div>
    <div class="col-4 my-auto">
    <%= link_to m.name, mountain_path(m) %>
    </div>
    <div class="col-3 my-auto">
    <%= m.country %>
    </div>
    <div class="col-3 my-auto">
    &#9734 <%= m.mountain_rating %>
    
    
    </div>
    </div>
    <% end %>
    </div>
    <div class="col-4">
    <div class="row">
    <h3 class="main-feature-title">Top Trails</h3>
    </div>
    <% @top_trails.each do |t| %>
      <div class="row">
      <div class="col-8">
      <%= link_to "#{t.name}", mountain_path(t.mountain) %>
      </div>
      <div class="col-3">
      &#9734 <%= t.trail_rating %>
      </div>
      </div>
    <% end %>

   <br>
   <br>
   <br>
    <div class="row">
    <h3 class="main-feature-title">Top Users</h3>
    </div>
      <% @top_users.each do |u| %>
        <div class="row">
        <div class="col-8">
        <%= u.first_name %>
        </div> 
        <div class="col-3">
        <%= u.number_of_visits %> trips
        </div>
        </div>
      <% end %>
    
    </div>
  </div>
</div>

app/views/mountains/show.html.erb
<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
<% end %>

<div class="container features">

<div class="row">
    <div class="col-4">
    <%= image_tag("#{@mountain.id}.jpg", style: 'margin: auto; width: 100%; border: 1px black') %>
    </div>
    <div class="col-4 my-auto">
    <h1><%= "#{@mountain.name}" %>, </h1>
    <h2><%= "#{@mountain.country}" %></h2>
    <p>&#9734 <%= @mountain.mountain_rating %></h4>
    </div>
    <div class="col-4 my-auto">
    <%if current_user.has_visited?(@mountain) %>
    <%= link_to "Log Another Trip to #{@mountain.name}", new_mountain_trip_path(@mountain) %>
    <%else%>
    To rate the trails at <%="#{@mountain.name}"%>,<br>
    <%= link_to "Log a Trip", new_mountain_trip_path(@mountain) %>
    <%end%>
    </div>
  </div>
<br>

  <div class="row">
    <div class="col-12">
    <h3 class="feature-title">Top Trails</h3>

<% @mountain.trails.each do |t| %>
    <div class="row">
    <div class="col-3">
    <strong><%= t.name %></strong> &#9734 <%= t.trail_rating %>
    </div>
    <div class="col-3">
    <strong>Level:</strong> <%= t.difficulty %>
    </div>
    <div class="col-4">
    <% if current_user.has_visited?(@mountain) %>
    <%= form_for Rating.new do |f| %>
        <%= f.label "Rate this Trail" %>
        <%= f.hidden_field :trail_id, value: t.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <% (1..5).each do |number| %>
        <%= f.radio_button :value, number %>
        <% end %>
        <%= f.submit "Submit" %>
    <% end %>
    <% end %>
    </div>
    </div>
    <br>
<% end %>
</div>
</div>