config/routes.rb
Rails.application.routes.draw do

  resources :ratings
  root "application#index"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/signup" => "users#new"
  post "/signup" => "users#create"
  post "/logout" => "sessions#destroy"

  get "/auth/:provider/callback" => "sessions#omniauth"

  resources :trips, only: [:new, :create, :edit, :update, :destroy]

  resources :mountains, only: [:show, :index] do
    resources :trips, only: [:new]
  end

  resources :users, only: [:new, :create, :edit, :show] do
    resources :trips, only: [:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :trips
    has_many :mountains, through: :trips
    has_many :trails, through: :mountains

    has_secure_password

    validates :first_name, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true


    def self.from_omniauth(auth)
        find_or_create_by(email: auth[:info][:email], first_name: auth[:info][:first_name]) do |user|
            user.password = SecureRandom.hex(15)
        end
    end

    def number_of_visits
        self.trips.count
    end

    def self.sort_by_top_users
        self.all.sort_by {|user| user.trips.count}.reverse
    end

    def self.top_5
        self.sort_by_top_users[0..4]
    end

    def top_5_trips
        self.trips.sort_by_date_descending[0..4]
    end

    def has_visited?(mountain)
        self.mountains.include?(mountain)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:new, :create]


    def new
        if logged_in?
            redirect_to mountains_path
        else
        @user = User.new
        end
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            redirect_to mountains_path
        else
            render :new
        end
    end

    def show
        if verify_user
            @user = User.find(params[:id])
            @trips = @user.top_5_trips
        else
            flash[:alert] = "You do not have permission to view this page."
            redirect_to mountains_path
        end
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :email, :password, :password_confirmation)
    end

    def verify_user
        User.find_by(id: params[:id]) == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_trips.html.erb
<% @trips.each do |t| %>
        <div class="row">
        <div class="col-3">
        <strong><%= t.date.to_time.strftime('%B %e, %Y') %></strong>
        </div>
        <div class="col-7">
        <%= link_to t.mountain.name, mountain_path(t.mountain) %>, <%= t.mountain.country %>
        </div>
        <div class="col-2">
        <%= link_to "Modify", edit_trip_path(t) %>
        </div>
        </div>
        <br>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this account from being saved:
    </h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="description">
<h1>On Piste</h1>
<p>Your ski travel resource.</p>

<%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>
    <%= f.submit value='Create Account'%>
<% end %>
<br>
<%= button_to "Sign Up with Google", '/auth/google_oauth2' %>

</div>

app/views/users/show.html.erb
<div class="container features">
<div class="row">
    <div class="col-12">
    <h1><%= "#{current_user.first_name}"%>'s Account</h1>
    </div>
</div>
<br>
<div class="row">
    <div class="col-12">
    <h3 class="feature-title">Recent Trips</h3>
        <%= render 'trips' %>
    </div>
</div>
<div class="row">
    <div class="col-12">
    <strong><%= link_to "All Trips", user_trips_path(current_user.id) %></strong>
    </div>
</div>